
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author admin
 */
public class TransferFrame extends javax.swing.JFrame {

    private static Database database;
    private static int index;
    private static User user;
    public TransferFrame(int i, Database database, User user) {
        this.database = database;
        this.user = user;
        index = i;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        target_Area = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cashArea = new javax.swing.JTextField();
        SendButton = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Please Enter the Account Index Which You Want to Transfer:");

        jLabel2.setText("Enter the Value That You Want to Transfer:");

        SendButton.setText("Send");
        SendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(target_Area, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cashArea, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(SendButton)))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(target_Area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(cashArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(SendButton)
                .addGap(79, 79, 79))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendButtonActionPerformed
       File file = new File("database.txt");
       double cash = Double.valueOf(cashArea.getText());
            int line_number=1;
            String line="";
            String s = target_Area.getText();
            StringBuilder sb = new StringBuilder();
        
            
            
        if(s.contains("A")||s.contains("B")||s.contains("C")||s.contains("D")||s.contains("E")||s.contains("F")||s.contains("G")) 
        {System.out.println("You can only enter numbers!");}  
        else{
                     int target = Integer.valueOf(target_Area.getText());
                        if(index == target) return;
                 try {
                     FileReader fr =new FileReader(file);
                     BufferedReader br = new BufferedReader(fr);
                   
                             while ((line = br.readLine()) != null) {
                                 if(index== line_number-1){ sb.append("ID:"+user.getId()+":Password:"+user.getPassword()+":"
                                +String.valueOf(Double.valueOf(user.getCash())-cash)+"\n");
                                 user.setCash(user.getCash()-cash);
                                   
                                }
                                 else if(target==line_number-1){
                                    database.getUsers().get(target).setCash(database.getUsers().get(target).getCash()+cash);
                                    String[] parts = line.split(":",5);
                                    String change = String.valueOf(Double.valueOf(parts[4])+cash);
                                    String temp = parts[0]+":"+parts[1]+":"+parts[2]+":"+parts[3]+":"+change;
                                    sb.append(temp+"\n");
                                }
                                else 
                                 {
                                     
                                     sb.append(line).append("\n");}
                                 line_number++;
                            }            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(TransferFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(TransferFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
 
                 
           try {    FileWriter fw=null;
                    fw = new FileWriter(file,false);
                    fw.write(sb.toString());
                    fw.close();
                    AccountFrame account = new AccountFrame(index, user, database);
                    account.setVisible(true);
                    this.setVisible(false);
           } catch (IOException ex) {
               Logger.getLogger(TransferFrame.class.getName()).log(Level.SEVERE, null, ex);
           }
   
        }
        
    }//GEN-LAST:event_SendButtonActionPerformed
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SendButton;
    private javax.swing.JTextField cashArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField target_Area;
    // End of variables declaration//GEN-END:variables
}
  
               /*  while ((line = br.readLine()) != null) {   
                        if(target==line_number-1)
                        {String temp ="";
                         String parts[] = line.split(":",5);
                         temp = parts[4];//eklemek istediğimiz cash değeri
                            System.out.println("line " +line);
                         String newline = line.replaceAll(temp,String.valueOf(Double.valueOf(temp)+cash) );
                         sb.append(newline);
                        }
                        
                       else {sb.append(line).append("\n");}
                    line_number++;
                 }*/